### ISSUE TITLE
2 "domains" required for http and https

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/siwecos-core-api#75]
The term "domain" in siwecos currently includes the protocol - at some places. At other places it doesn't. This leads to some inconsistencies and also to the inconvenient situation that you need to register 2 "domains" should you want to have http and https be scanned.

Maybe it's better to just register the domain and scan both, http and https. As far as I know, the WS_TLS scanner already does this.

Questions mainly are:

1. Do the scanners require changes?
2. Should we just initiate double the amount of scans (I don't think so)
3. Should we initiate double the amount of scans if http does NOT redirect to https?
4. Or should we simply have a check: http is redirect to https and if not this is a bad score?
…

**Comment by Skeeve** [comment]
Related to https://github.com/SIWECOS/siwecos-business-layer/issues/3

**Comment by Lednerb** [comment]
IMHO we should go with 4.

HTTPS should always be used. There is no excuse for not using it anymore since certificates are free via Let's Encrypt.

There should be always a test if there is a redirect from HTTP to HTTPS, if not, set a 0-rating and tell the user, that this is not good (Google Chrome marks the pages not secure).

Don't do any further scans on HTTP, it's not secure, don't waste time and resources.

**Comment by Weegy** [comment]
Die Protokolleingabe soll nicht mehr erforderlich sein. 

Core API testet Port und teilt den Scanner mit.

Testreihenfolge: 443 - 80 - www:443 - www:80

**Comment by Weegy** [comment]
Schätzung 2h (Guzzle / Curl)

**Comment by Lednerb** [comment]
PR opened #151

**Comment by Lednerb** [comment]
Done.
